# require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'examples/**'

# BEGIN
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
# END
